requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue!
requestInfoLabelToAdd: more info needed
sentimentBotToxicityThreshold: .7
sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users.
